import React from 'react';
import { Game } from '../types';
import GameCard from './GameCard';
import { TicTacToeIcon } from './icons/TicTacToeIcon';
import { RockPaperScissorsIcon } from './icons/RockPaperScissorsIcon';
import { ChessIcon } from './icons/ChessIcon';
import { ConnectFourIcon } from './icons/ConnectFourIcon';
import { MemoryMatchIcon } from './icons/MemoryMatchIcon';
import { SudokuIcon } from './icons/SudokuIcon';
import { HangmanIcon } from './icons/HangmanIcon';

interface GameLibraryProps {
  onSelectGame: (game: Game) => void;
}

const games: Game[] = [
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    description: 'The classic game of Xs and Os. Play against a friend.',
    icon: <TicTacToeIcon />,
  },
  {
    id: 'rock-paper-scissors',
    name: 'Rock Paper Scissors',
    description: 'Challenge the Gemini AI in this timeless game of chance.',
    icon: <RockPaperScissorsIcon />,
  },
  {
    id: 'chess',
    name: 'Chess',
    description: 'The ultimate game of strategy. Play locally or online via correspondence.',
    icon: <ChessIcon />,
  },
   {
    id: 'connect-four',
    name: 'Connect Four',
    description: 'Try to get four in a row against a strategic local AI opponent.',
    icon: <ConnectFourIcon />,
  },
  {
    id: 'memory-match',
    name: 'Memory Match',
    description: 'Test your memory against an AI with selectable difficulty levels.',
    icon: <MemoryMatchIcon />,
  },
  {
    id: 'sudoku',
    name: 'Sudoku',
    description: 'A classic puzzle of logic and numbers. Get hints from Gemini.',
    icon: <SudokuIcon />,
  },
  {
    id: 'hangman',
    name: 'Hangman',
    description: 'Guess the secret word generated by Gemini before time runs out.',
    icon: <HangmanIcon />,
  },
];

const GameLibrary: React.FC<GameLibraryProps> = ({ onSelectGame }) => {
  return (
    <div className="flex flex-col items-center">
      <h2 className="text-3xl md:text-4xl font-bold mb-2 text-center">Welcome to the Arcade!</h2>
      <p className="text-gray-400 mb-8 text-center max-w-lg">
        Select a game below to start playing. Some games feature a Gemini-powered AI for you to challenge.
      </p>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 w-full max-w-5xl">
        {games.map((game) => (
          <GameCard key={game.id} game={game} onSelect={onSelectGame} />
        ))}
      </div>
    </div>
  );
};

export default GameLibrary;